/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBoardRouteImport } from './routes/_app/board'
import { Route as AppBudRouteImport } from './routes/_app/bud'
import { Route as AppCommunitiesRouteImport } from './routes/_app/communities'
import { Route as AppConnectRouteImport } from './routes/_app/connect'
import { Route as AppCreatorRouteImport } from './routes/_app/creator'
import { Route as AppDiscoveryRouteImport } from './routes/_app/discovery'
import { Route as AppFeedbackRouteImport } from './routes/_app/feedback'
import { Route as AppFixerRouteImport } from './routes/_app/fixer'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppLiveRouteImport } from './routes/_app/live'
import { Route as AppMarketRouteImport } from './routes/_app/market'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppMoneyRouteImport } from './routes/_app/money'
import { Route as AppNewsRouteImport } from './routes/_app/news'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppPodcastsRouteImport } from './routes/_app/podcasts'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppRiffRouteImport } from './routes/_app/riff'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSellRouteImport } from './routes/_app/sell'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSocialRouteImport } from './routes/_app/social'
import { Route as AppSpillRouteImport } from './routes/_app/spill'
import { Route as AppStudiesRouteImport } from './routes/_app/studies'
import { Route as AppTutorRouteImport } from './routes/_app/tutor'
import { Route as AppWatchRouteImport } from './routes/_app/watch'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as AppAudioIdRouteImport } from './routes/_app/audio.$id'
import { Route as AppBoardIdRouteImport } from './routes/_app/board.$id'
import { Route as AppBudCommunitiesRouteImport } from './routes/_app/bud.communities'
import { Route as AppBudFixerRouteImport } from './routes/_app/bud.fixer'
import { Route as AppCommunitiesCommunityIdRouteImport } from './routes/_app/communities/$communityId'
import { Route as AppCommunitiesIdRouteImport } from './routes/_app/communities.$id'
import { Route as AppMarketIndexRouteImport } from './routes/_app/market/index'
import { Route as AppMarketIdRouteImport } from './routes/_app/market.$id'
import { Route as AppMarketListingIdRouteImport } from './routes/_app/market/$listingId'
import { Route as AppMessagesIdRouteImport } from './routes/_app/messages.$id'
import { Route as AppRiffIdRouteImport } from './routes/_app/riff.$id'
import { Route as AppSpillIdRouteImport } from './routes/_app/spill.$id'
import { Route as AppUHandleRouteImport } from './routes/_app/u.$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaIdRouteImport } from './routes/api/media.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppBudRoute = AppBudRouteImport.update({
  id: '/bud',
  path: '/bud',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesRoute = AppCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppCreatorRoute = AppCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryRoute = AppDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppFixerRoute = AppFixerRouteImport.update({
  id: '/fixer',
  path: '/fixer',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyRoute = AppMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPodcastsRoute = AppPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRiffRoute = AppRiffRouteImport.update({
  id: '/riff',
  path: '/riff',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSellRoute = AppSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSpillRoute = AppSpillRouteImport.update({
  id: '/spill',
  path: '/spill',
  getParentRoute: () => AppRoute,
} as any)
const AppStudiesRoute = AppStudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchRoute = AppWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppAudioIdRoute = AppAudioIdRouteImport.update({
  id: '/audio/$id',
  path: '/audio/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardIdRoute = AppBoardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBudCommunitiesRoute = AppBudCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AppBudRoute,
} as any)
const AppBudFixerRoute = AppBudFixerRouteImport.update({
  id: '/fixer',
  path: '/fixer',
  getParentRoute: () => AppBudRoute,
} as any)
const AppCommunitiesCommunityIdRoute =
  AppCommunitiesCommunityIdRouteImport.update({
    id: '/$communityId',
    path: '/$communityId',
    getParentRoute: () => AppCommunitiesRoute,
  } as any)
const AppCommunitiesIdRoute = AppCommunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCommunitiesRoute,
} as any)
const AppMarketIndexRoute = AppMarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMarketRoute,
} as any)
const AppMarketIdRoute = AppMarketIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMarketRoute,
} as any)
const AppMarketListingIdRoute = AppMarketListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => AppMarketRoute,
} as any)
const AppMessagesIdRoute = AppMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppRiffIdRoute = AppRiffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRiffRoute,
} as any)
const AppSpillIdRoute = AppSpillIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSpillRoute,
} as any)
const AppUHandleRoute = AppUHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/board': typeof AppBoardRouteWithChildren
  '/bud': typeof AppBudRouteWithChildren
  '/communities': typeof AppCommunitiesRouteWithChildren
  '/connect': typeof AppConnectRoute
  '/creator': typeof AppCreatorRoute
  '/discovery': typeof AppDiscoveryRoute
  '/feedback': typeof AppFeedbackRoute
  '/fixer': typeof AppFixerRoute
  '/help': typeof AppHelpRoute
  '/live': typeof AppLiveRoute
  '/market': typeof AppMarketRouteWithChildren
  '/messages': typeof AppMessagesRouteWithChildren
  '/money': typeof AppMoneyRoute
  '/news': typeof AppNewsRoute
  '/notifications': typeof AppNotificationsRoute
  '/podcasts': typeof AppPodcastsRoute
  '/profile': typeof AppProfileRoute
  '/riff': typeof AppRiffRouteWithChildren
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/sell': typeof AppSellRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
  '/spill': typeof AppSpillRouteWithChildren
  '/studies': typeof AppStudiesRoute
  '/tutor': typeof AppTutorRoute
  '/watch': typeof AppWatchRoute
  '/welcome': typeof AppWelcomeRoute
  '/audio/$id': typeof AppAudioIdRoute
  '/board/$id': typeof AppBoardIdRoute
  '/bud/communities': typeof AppBudCommunitiesRoute
  '/bud/fixer': typeof AppBudFixerRoute
  '/communities/$communityId': typeof AppCommunitiesCommunityIdRoute
  '/communities/$id': typeof AppCommunitiesIdRoute
  '/market/$id': typeof AppMarketIdRoute
  '/market/$listingId': typeof AppMarketListingIdRoute
  '/messages/$id': typeof AppMessagesIdRoute
  '/riff/$id': typeof AppRiffIdRoute
  '/spill/$id': typeof AppSpillIdRoute
  '/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/market/': typeof AppMarketIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/board': typeof AppBoardRouteWithChildren
  '/bud': typeof AppBudRouteWithChildren
  '/communities': typeof AppCommunitiesRouteWithChildren
  '/connect': typeof AppConnectRoute
  '/creator': typeof AppCreatorRoute
  '/discovery': typeof AppDiscoveryRoute
  '/feedback': typeof AppFeedbackRoute
  '/fixer': typeof AppFixerRoute
  '/help': typeof AppHelpRoute
  '/live': typeof AppLiveRoute
  '/messages': typeof AppMessagesRouteWithChildren
  '/money': typeof AppMoneyRoute
  '/news': typeof AppNewsRoute
  '/notifications': typeof AppNotificationsRoute
  '/podcasts': typeof AppPodcastsRoute
  '/profile': typeof AppProfileRoute
  '/riff': typeof AppRiffRouteWithChildren
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/sell': typeof AppSellRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
  '/spill': typeof AppSpillRouteWithChildren
  '/studies': typeof AppStudiesRoute
  '/tutor': typeof AppTutorRoute
  '/watch': typeof AppWatchRoute
  '/welcome': typeof AppWelcomeRoute
  '/': typeof AppIndexRoute
  '/audio/$id': typeof AppAudioIdRoute
  '/board/$id': typeof AppBoardIdRoute
  '/bud/communities': typeof AppBudCommunitiesRoute
  '/bud/fixer': typeof AppBudFixerRoute
  '/communities/$communityId': typeof AppCommunitiesCommunityIdRoute
  '/communities/$id': typeof AppCommunitiesIdRoute
  '/market/$id': typeof AppMarketIdRoute
  '/market/$listingId': typeof AppMarketListingIdRoute
  '/messages/$id': typeof AppMessagesIdRoute
  '/riff/$id': typeof AppRiffIdRoute
  '/spill/$id': typeof AppSpillIdRoute
  '/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/market': typeof AppMarketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/board': typeof AppBoardRouteWithChildren
  '/_app/bud': typeof AppBudRouteWithChildren
  '/_app/communities': typeof AppCommunitiesRouteWithChildren
  '/_app/connect': typeof AppConnectRoute
  '/_app/creator': typeof AppCreatorRoute
  '/_app/discovery': typeof AppDiscoveryRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/fixer': typeof AppFixerRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/live': typeof AppLiveRoute
  '/_app/market': typeof AppMarketRouteWithChildren
  '/_app/messages': typeof AppMessagesRouteWithChildren
  '/_app/money': typeof AppMoneyRoute
  '/_app/news': typeof AppNewsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/podcasts': typeof AppPodcastsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/riff': typeof AppRiffRouteWithChildren
  '/_app/saved': typeof AppSavedRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/sell': typeof AppSellRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/social': typeof AppSocialRoute
  '/_app/spill': typeof AppSpillRouteWithChildren
  '/_app/studies': typeof AppStudiesRoute
  '/_app/tutor': typeof AppTutorRoute
  '/_app/watch': typeof AppWatchRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/audio/$id': typeof AppAudioIdRoute
  '/_app/board/$id': typeof AppBoardIdRoute
  '/_app/bud/communities': typeof AppBudCommunitiesRoute
  '/_app/bud/fixer': typeof AppBudFixerRoute
  '/_app/communities/$communityId': typeof AppCommunitiesCommunityIdRoute
  '/_app/communities/$id': typeof AppCommunitiesIdRoute
  '/_app/market/$id': typeof AppMarketIdRoute
  '/_app/market/$listingId': typeof AppMarketListingIdRoute
  '/_app/messages/$id': typeof AppMessagesIdRoute
  '/_app/riff/$id': typeof AppRiffIdRoute
  '/_app/spill/$id': typeof AppSpillIdRoute
  '/_app/u/$handle': typeof AppUHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/_app/market/': typeof AppMarketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/board'
    | '/bud'
    | '/communities'
    | '/connect'
    | '/creator'
    | '/discovery'
    | '/feedback'
    | '/fixer'
    | '/help'
    | '/live'
    | '/market'
    | '/messages'
    | '/money'
    | '/news'
    | '/notifications'
    | '/podcasts'
    | '/profile'
    | '/riff'
    | '/saved'
    | '/search'
    | '/sell'
    | '/settings'
    | '/social'
    | '/spill'
    | '/studies'
    | '/tutor'
    | '/watch'
    | '/welcome'
    | '/audio/$id'
    | '/board/$id'
    | '/bud/communities'
    | '/bud/fixer'
    | '/communities/$communityId'
    | '/communities/$id'
    | '/market/$id'
    | '/market/$listingId'
    | '/messages/$id'
    | '/riff/$id'
    | '/spill/$id'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/media/$id'
    | '/market/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/board'
    | '/bud'
    | '/communities'
    | '/connect'
    | '/creator'
    | '/discovery'
    | '/feedback'
    | '/fixer'
    | '/help'
    | '/live'
    | '/messages'
    | '/money'
    | '/news'
    | '/notifications'
    | '/podcasts'
    | '/profile'
    | '/riff'
    | '/saved'
    | '/search'
    | '/sell'
    | '/settings'
    | '/social'
    | '/spill'
    | '/studies'
    | '/tutor'
    | '/watch'
    | '/welcome'
    | '/'
    | '/audio/$id'
    | '/board/$id'
    | '/bud/communities'
    | '/bud/fixer'
    | '/communities/$communityId'
    | '/communities/$id'
    | '/market/$id'
    | '/market/$listingId'
    | '/messages/$id'
    | '/riff/$id'
    | '/spill/$id'
    | '/u/$handle'
    | '/api/auth/$'
    | '/api/media/$id'
    | '/market'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/board'
    | '/_app/bud'
    | '/_app/communities'
    | '/_app/connect'
    | '/_app/creator'
    | '/_app/discovery'
    | '/_app/feedback'
    | '/_app/fixer'
    | '/_app/help'
    | '/_app/live'
    | '/_app/market'
    | '/_app/messages'
    | '/_app/money'
    | '/_app/news'
    | '/_app/notifications'
    | '/_app/podcasts'
    | '/_app/profile'
    | '/_app/riff'
    | '/_app/saved'
    | '/_app/search'
    | '/_app/sell'
    | '/_app/settings'
    | '/_app/social'
    | '/_app/spill'
    | '/_app/studies'
    | '/_app/tutor'
    | '/_app/watch'
    | '/_app/welcome'
    | '/_app/'
    | '/_app/audio/$id'
    | '/_app/board/$id'
    | '/_app/bud/communities'
    | '/_app/bud/fixer'
    | '/_app/communities/$communityId'
    | '/_app/communities/$id'
    | '/_app/market/$id'
    | '/_app/market/$listingId'
    | '/_app/messages/$id'
    | '/_app/riff/$id'
    | '/_app/spill/$id'
    | '/_app/u/$handle'
    | '/api/auth/$'
    | '/api/media/$id'
    | '/_app/market/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board': {
      id: '/_app/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bud': {
      id: '/_app/bud'
      path: '/bud'
      fullPath: '/bud'
      preLoaderRoute: typeof AppBudRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities': {
      id: '/_app/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AppCommunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creator': {
      id: '/_app/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof AppCreatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discovery': {
      id: '/_app/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AppDiscoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fixer': {
      id: '/_app/fixer'
      path: '/fixer'
      fullPath: '/fixer'
      preLoaderRoute: typeof AppFixerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market': {
      id: '/_app/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money': {
      id: '/_app/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AppMoneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news': {
      id: '/_app/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/podcasts': {
      id: '/_app/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof AppPodcastsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/riff': {
      id: '/_app/riff'
      path: '/riff'
      fullPath: '/riff'
      preLoaderRoute: typeof AppRiffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sell': {
      id: '/_app/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AppSellRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social': {
      id: '/_app/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spill': {
      id: '/_app/spill'
      path: '/spill'
      fullPath: '/spill'
      preLoaderRoute: typeof AppSpillRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studies': {
      id: '/_app/studies'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof AppStudiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watch': {
      id: '/_app/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof AppWatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audio/$id': {
      id: '/_app/audio/$id'
      path: '/audio/$id'
      fullPath: '/audio/$id'
      preLoaderRoute: typeof AppAudioIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board/$id': {
      id: '/_app/board/$id'
      path: '/$id'
      fullPath: '/board/$id'
      preLoaderRoute: typeof AppBoardIdRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/_app/bud/communities': {
      id: '/_app/bud/communities'
      path: '/communities'
      fullPath: '/bud/communities'
      preLoaderRoute: typeof AppBudCommunitiesRouteImport
      parentRoute: typeof AppBudRoute
    }
    '/_app/bud/fixer': {
      id: '/_app/bud/fixer'
      path: '/fixer'
      fullPath: '/bud/fixer'
      preLoaderRoute: typeof AppBudFixerRouteImport
      parentRoute: typeof AppBudRoute
    }
    '/_app/communities/$communityId': {
      id: '/_app/communities/$communityId'
      path: '/$communityId'
      fullPath: '/communities/$communityId'
      preLoaderRoute: typeof AppCommunitiesCommunityIdRouteImport
      parentRoute: typeof AppCommunitiesRoute
    }
    '/_app/communities/$id': {
      id: '/_app/communities/$id'
      path: '/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof AppCommunitiesIdRouteImport
      parentRoute: typeof AppCommunitiesRoute
    }
    '/_app/market/': {
      id: '/_app/market/'
      path: '/'
      fullPath: '/market/'
      preLoaderRoute: typeof AppMarketIndexRouteImport
      parentRoute: typeof AppMarketRoute
    }
    '/_app/market/$id': {
      id: '/_app/market/$id'
      path: '/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof AppMarketIdRouteImport
      parentRoute: typeof AppMarketRoute
    }
    '/_app/market/$listingId': {
      id: '/_app/market/$listingId'
      path: '/$listingId'
      fullPath: '/market/$listingId'
      preLoaderRoute: typeof AppMarketListingIdRouteImport
      parentRoute: typeof AppMarketRoute
    }
    '/_app/messages/$id': {
      id: '/_app/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AppMessagesIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/_app/riff/$id': {
      id: '/_app/riff/$id'
      path: '/$id'
      fullPath: '/riff/$id'
      preLoaderRoute: typeof AppRiffIdRouteImport
      parentRoute: typeof AppRiffRoute
    }
    '/_app/spill/$id': {
      id: '/_app/spill/$id'
      path: '/$id'
      fullPath: '/spill/$id'
      preLoaderRoute: typeof AppSpillIdRouteImport
      parentRoute: typeof AppSpillRoute
    }
    '/_app/u/$handle': {
      id: '/_app/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof AppUHandleRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppBoardRouteChildren {
  AppBoardIdRoute: typeof AppBoardIdRoute
}

const AppBoardRouteChildren: AppBoardRouteChildren = {
  AppBoardIdRoute: AppBoardIdRoute,
}

const AppBoardRouteWithChildren = AppBoardRoute._addFileChildren(
  AppBoardRouteChildren,
)

interface AppBudRouteChildren {
  AppBudCommunitiesRoute: typeof AppBudCommunitiesRoute
  AppBudFixerRoute: typeof AppBudFixerRoute
}

const AppBudRouteChildren: AppBudRouteChildren = {
  AppBudCommunitiesRoute: AppBudCommunitiesRoute,
  AppBudFixerRoute: AppBudFixerRoute,
}

const AppBudRouteWithChildren =
  AppBudRoute._addFileChildren(AppBudRouteChildren)

interface AppCommunitiesRouteChildren {
  AppCommunitiesCommunityIdRoute: typeof AppCommunitiesCommunityIdRoute
  AppCommunitiesIdRoute: typeof AppCommunitiesIdRoute
}

const AppCommunitiesRouteChildren: AppCommunitiesRouteChildren = {
  AppCommunitiesCommunityIdRoute: AppCommunitiesCommunityIdRoute,
  AppCommunitiesIdRoute: AppCommunitiesIdRoute,
}

const AppCommunitiesRouteWithChildren = AppCommunitiesRoute._addFileChildren(
  AppCommunitiesRouteChildren,
)

interface AppMarketRouteChildren {
  AppMarketIdRoute: typeof AppMarketIdRoute
  AppMarketListingIdRoute: typeof AppMarketListingIdRoute
  AppMarketIndexRoute: typeof AppMarketIndexRoute
}

const AppMarketRouteChildren: AppMarketRouteChildren = {
  AppMarketIdRoute: AppMarketIdRoute,
  AppMarketListingIdRoute: AppMarketListingIdRoute,
  AppMarketIndexRoute: AppMarketIndexRoute,
}

const AppMarketRouteWithChildren = AppMarketRoute._addFileChildren(
  AppMarketRouteChildren,
)

interface AppMessagesRouteChildren {
  AppMessagesIdRoute: typeof AppMessagesIdRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesIdRoute: AppMessagesIdRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppRiffRouteChildren {
  AppRiffIdRoute: typeof AppRiffIdRoute
}

const AppRiffRouteChildren: AppRiffRouteChildren = {
  AppRiffIdRoute: AppRiffIdRoute,
}

const AppRiffRouteWithChildren =
  AppRiffRoute._addFileChildren(AppRiffRouteChildren)

interface AppSpillRouteChildren {
  AppSpillIdRoute: typeof AppSpillIdRoute
}

const AppSpillRouteChildren: AppSpillRouteChildren = {
  AppSpillIdRoute: AppSpillIdRoute,
}

const AppSpillRouteWithChildren = AppSpillRoute._addFileChildren(
  AppSpillRouteChildren,
)

interface AppRouteChildren {
  AppBoardRoute: typeof AppBoardRouteWithChildren
  AppBudRoute: typeof AppBudRouteWithChildren
  AppCommunitiesRoute: typeof AppCommunitiesRouteWithChildren
  AppConnectRoute: typeof AppConnectRoute
  AppCreatorRoute: typeof AppCreatorRoute
  AppDiscoveryRoute: typeof AppDiscoveryRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppFixerRoute: typeof AppFixerRoute
  AppHelpRoute: typeof AppHelpRoute
  AppLiveRoute: typeof AppLiveRoute
  AppMarketRoute: typeof AppMarketRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppMoneyRoute: typeof AppMoneyRoute
  AppNewsRoute: typeof AppNewsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPodcastsRoute: typeof AppPodcastsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRiffRoute: typeof AppRiffRouteWithChildren
  AppSavedRoute: typeof AppSavedRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSellRoute: typeof AppSellRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppSpillRoute: typeof AppSpillRouteWithChildren
  AppStudiesRoute: typeof AppStudiesRoute
  AppTutorRoute: typeof AppTutorRoute
  AppWatchRoute: typeof AppWatchRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAudioIdRoute: typeof AppAudioIdRoute
  AppUHandleRoute: typeof AppUHandleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoardRoute: AppBoardRouteWithChildren,
  AppBudRoute: AppBudRouteWithChildren,
  AppCommunitiesRoute: AppCommunitiesRouteWithChildren,
  AppConnectRoute: AppConnectRoute,
  AppCreatorRoute: AppCreatorRoute,
  AppDiscoveryRoute: AppDiscoveryRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppFixerRoute: AppFixerRoute,
  AppHelpRoute: AppHelpRoute,
  AppLiveRoute: AppLiveRoute,
  AppMarketRoute: AppMarketRouteWithChildren,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppMoneyRoute: AppMoneyRoute,
  AppNewsRoute: AppNewsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPodcastsRoute: AppPodcastsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRiffRoute: AppRiffRouteWithChildren,
  AppSavedRoute: AppSavedRoute,
  AppSearchRoute: AppSearchRoute,
  AppSellRoute: AppSellRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialRoute: AppSocialRoute,
  AppSpillRoute: AppSpillRouteWithChildren,
  AppStudiesRoute: AppStudiesRoute,
  AppTutorRoute: AppTutorRoute,
  AppWatchRoute: AppWatchRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppAudioIdRoute: AppAudioIdRoute,
  AppUHandleRoute: AppUHandleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
